### ISSUE TITLE
Upload tests logs from BEP fails

### ISSUE THREAD

**Issue by comius** [bazelbuild/continuous-integration#1038]
This happened on bazelisk build after test failure:

```
(04:08:41) [23 / 26] 1 / 3 tests, 1 failed;  1 action; last test: //:go_bazelisk_test
--
  | Testing //:py_bazelisk_test; 1s remote-cache, linux-sandbox
  | [Errno 13] Permission denied: '/go_bazelisk_test'
  | buildkite-agent artifact upload
  | 2020-09-27 04:08:44 FATAL  Missing upload paths. See: `buildkite-agent artifact upload --help`
  | Exception in thread Thread-1:
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
  | self.run()
  | File "/usr/local/lib/python3.6/threading.py", line 864, in run
  | self._target(*self._args, **self._kwargs)
  | File "bazelci.py", line 1966, in upload_test_logs_from_bep
  | execute_command(["buildkite-agent", "artifact", "upload", ";".join(test_logs)])
  | File "bazelci.py", line 2062, in execute_command
  | args, shell=shell, check=fail_if_nonzero, env=os.environ, cwd=cwd
  | File "/usr/local/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)
```

Link: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1673#72e7b63c-bd1b-4ff1-a5b6-20943b5fbf4f

**Comment by comius** [comment]
Stale
