### ISSUE TITLE
Remote cache exceptions (Connection refused) on macOS workers

### ISSUE THREAD

**Issue by jin** [bazelbuild/continuous-integration#1103]
Seeing this on rules_jvm_external:

https://buildkite.com/bazel/rules-jvm-external/builds/1892#c0c1580e-74c3-49af-905d-731c847aed26

```
(11:17:55) WARNING: Writing to Remote Cache:
--
  | com.google.devtools.build.lib.remote.BulkTransferException
  | at com.google.devtools.build.lib.remote.RemoteCache.waitForBulkTransfer(RemoteCache.java:227)
  | at com.google.devtools.build.lib.remote.RemoteCache.uploadOutputs(RemoteCache.java:201)
  | at com.google.devtools.build.lib.remote.RemoteCache.upload(RemoteCache.java:139)
  | at com.google.devtools.build.lib.remote.RemoteCache.upload(RemoteCache.java:156)
  | at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:283)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:145)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:102)
  | at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
  | at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:65)
  | at com.google.devtools.build.lib.rules.java.JavaCompileAction.beginExecution(JavaCompileAction.java:357)
  | at com.google.devtools.build.lib.actions.Action.execute(Action.java:127)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:855)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1016)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:975)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:129)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:81)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:472)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:834)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:307)
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /100.107.73.148:80
  | Caused by: java.net.ConnectException: Connection refused
  | at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
  | at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
  | at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
  | at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /100.107.73.148:80
  | Caused by: java.net.ConnectException: Connection refused
  | at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
  | at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
  | at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
  | at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /100.107.73.148:80
  | Caused by: java.net.ConnectException: Connection refused
  | at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
  | at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
  | at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
  | at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /100.107.73.148:80
  | Caused by: java.net.ConnectException: Connection refused
  | at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
  | at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
  | at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
  | at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /100.107.73.148:80
  | Caused by: java.net.ConnectException: Connection refused
  | at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
  | at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
  | at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
  | at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /100.107.73.148:80
  | Caused by: java.net.ConnectException: Connection refused
  | at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
  | at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
  | at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
  | at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by philwo** [comment]
I'm currently maintaining the remote cache server - these warnings should disappear once I'm done (~30 minutes). :) They should not cause the build to fail or any issues.

**Comment by philwo** [comment]
Should be fixed now.
