### ISSUE TITLE
Job fails with jenkins stacktrace

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#111]
We have several jobs failing with the following stack trace:
```
java.io.IOException: remote file operation failed: /home/ci/workspace/rules_closure-variation=,node=ubuntu_16.04-x86_64 at hudson.remoting.Channel@479e0ec6:JNLP4-connect connection from ubuntu-16-04-slave-3.c.bazel-public.internal/192.168.59.10:44960: java.io.IOException: Remote call on JNLP4-connect connection from ubuntu-16-04-slave-3.c.bazel-public.internal/192.168.59.10:44960 failed
	at hudson.FilePath.act(FilePath.java:992)
	at hudson.FilePath.act(FilePath.java:974)
	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:103)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:128)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:149)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:78)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:65)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Remote call on JNLP4-connect connection from ubuntu-16-04-slave-3.c.bazel-public.internal/192.168.59.10:44960 failed
	at hudson.remoting.Channel.call(Channel.java:838)
	at hudson.FilePath.act(FilePath.java:985)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins
	at hudson.util.io.ParserConfigurator.applyConfiguration(ParserConfigurator.java:78)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:124)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:302)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:244)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:175)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:154)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:126)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:132)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:107)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:748)
	at ......remote call to JNLP4-connect connection from ubuntu-16-04-slave-3.c.bazel-public.internal/192.168.59.10:44960(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	... 15 more
Finished: FAILURE
```

**Comment by damienmg** [comment]
Ok this is coming from the Junit archiver...

**Comment by damienmg** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-34108 seems to be that issue, weird it is qualified as "minor"

**Comment by damienmg** [comment]
Another similar issue: https://issues.jenkins-ci.org/browse/JENKINS-44700

**Comment by damienmg** [comment]
Retrying the build of buildifier, could be a problem with job interupted in the middle of a remote op.

**Comment by damienmg** [comment]
Humm this is super deterministic, once the release pipeline has run, I'll try to restart the jenkins server to get back to a clean state.

**Comment by damienmg** [comment]
Restarting the server made the error goes away. Might have a problem in our FilePath manipulation somewhere that set that up.
