### ISSUE TITLE
Github Webhook failures

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#150]
This is still happening, from the Jenkins logs:
```
Could not update commit status of the Pull Request on GitHub.
java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/bazelbuild/rules_go/statuses/a1795a81b94a161480de37be771055a1512cc758
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun
```

**Comment by damienmg** [comment]
Where do you get that log from? The latest PR vetting from rules_go says success...

**Comment by damienmg** [comment]
Lowering priority because it is not happening atm

**Comment by katre** [comment]
ci.bazel.io -> Manage Jenkins -> System Log -> All Jenkins Logs

I don't see it happening again, however, so I will close this.
