### ISSUE TITLE
locale seems to be wrong on some Mac machines

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#1582]
https://buildkite.com/bazel/google-bazel-presubmit/builds/65572#018778e4-6cdb-4e62-9d8c-67558aa6231d
```
There were 4 failures:
1) testCriticalPathMiddleman(com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest)
value of           : toStringSummary()
expected to contain: Critical Path: 8.00s
but was            : Critical Path: 8,00s, Remote (100.00% of the time): [queue: 0.00%, setup: 0.00%, process: 100.00%]
	at com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest.checkCriticalPath(CriticalPathComputerTest.java:1069)
	at com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest.testCriticalPathMiddleman(CriticalPathComputerTest.java:244)
2) testCriticalPathOneAction(com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest)
value of           : toStringSummary()
expected to contain: Critical Path: 2.00s
but was            : Critical Path: 2,00s, Remote (50.00% of the time): [queue: 0.00%, setup: 0.00%, process: 50.00%]
	at com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest.checkCriticalPath(CriticalPathComputerTest.java:1069)
	at com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest.testCriticalPathOneAction(CriticalPathComputerTest.java:160)
3) testWallTime(com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest)
value of           : toStringSummary()
expected to contain: Critical Path: 2.00s
but was            : Critical Path: 2,00s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
	at com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest.checkCriticalPath(CriticalPathComputerTest.java:1048)
	at com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest.testWallTime(CriticalPathComputerTest.java:563)
4) testCriticalPathQueueTimeWithoutRetries(com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest)
value of           : toStringSummary()
expected to contain: Critical Path: 8.00s
but was            : Critical Path: 8,00s, Remote (50.00% of the time): [queue: 12.50%, setup: 0.00%, process: 12.50%, other: 25.00%]
	at com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest.checkCriticalPath(CriticalPathComputerTest.java:1069)
	at com.google.devtools.build.lib.metrics.criticalpath.CriticalPathComputerTest.testCriticalPathQueueTimeWithoutRetries(CriticalPathComputerTest.java:182)
```

This happened on `bk-imacpro-15`, @fweikert do you think it is related to recent Mac machine updates?

**Comment by fmeum** [comment]
A run with the failure: https://buildkite.com/bazel/bazel-bazel/builds/22873#01877edb-39f6-4954-af3d-8f4791850552

Another way to fix this could be to set JVM flags for all tests, similar to what Bazel itself does on `blaze.cc`:
https://cs.opensource.google/bazel/bazel/+/2d2ff7e0959c6ac54a8faa84b03e0698abe26cb7:src/main/cpp/blaze.cc;l=409-411

**Comment by meteorcloudy** [comment]
Bazel breakages is now fixed by https://github.com/bazelbuild/bazel/commit/98123ba8cd0f19bc1be70758e96d7d1c5b212c17
