### ISSUE TITLE
darwin jobs gets weird failure

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#16]
```
FATAL: null
java.lang.NullPointerException
	at hudson.model.Slave.createLauncher(Slave.java:387)
	at hudson.model.AbstractBuild$AbstractBuildExecution.createLauncher(AbstractBuild.java:561)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:492)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```
from http://ci.bazel.io/job/bazel-tests/141/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/console

Also darwin 2 is down

**Comment by damienmg** [comment]
darwin 2 is up again, rebooting did the trick

**Comment by damienmg** [comment]
The other problem seems like a flake in Jenkins themselves, it selected a slave that was down. Closing this bug
