### ISSUE TITLE
"Bazel build" is failing in downstream pipeline on both windows and ubuntu. 

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/continuous-integration#1612]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2992#0187da38-b7c8-4e94-a10a-3afe66a12e34

Platform : ubuntu, Windows

Ubuntu logs: 

```
(02:58:46) [10,946 / 11,032] 596 / 727 tests, 1 failed; 30 actions, 16 running; last test: .../shell/bazel:bazel_hermetic_sandboxing_test
```

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2992#0187da38-b7d5-4241-8650-e3355e8e6475

Windows logs: 
```
 ERROR bazelci_agent::artifact::upload: The system cannot find the file specified. (os error 2)
--
  | Error: The system cannot find the file specified. (os error 2)
  | Exception in thread Thread-1:
  | Traceback (most recent call last):
  | File "C:\python3\lib\threading.py", line 973, in _bootstrap_inner
  | self.run()
  | File "C:\python3\lib\threading.py", line 910, in run
  | self._target(*self._args, **self._kwargs)
  | File "c:\b\bk-windows-p38h\bazel\bazel-at-head-plus-downstream\bazelci.py", line 2379, in upload_test_logs_from_bep
  | execute_command(
  | File "c:\b\bk-windows-p38h\bazel\bazel-at-head-plus-downstream\bazelci.py", line 2429, in execute_command
  | return subprocess.run(
  | File "C:\python3\lib\subprocess.py", line 528, in run
  | raise CalledProcessError(retcode, process.args,
  | subprocess.CalledProcessError: Command '['C:\\temp\\tmp943pl4nf\\bazelci-agent.exe', 'artifact', 'upload', '--delay=5', '--mode=buildkite', '--build_event_json_file=C:\\temp\\tmp943pl4nf\\test_bep.json']' returned non-zero exit status 1.
  | Traceback (most recent call last):
  | File "c:\b\bk-windows-p38h\bazel\bazel-at-head-plus-downstream\bazelci.py", line 3762, in <module>
  | sys.exit(main())
  | File "c:\b\bk-windows-p38h\bazel\bazel-at-head-plus-downstream\bazelci.py", line 3729, in main
  | execute_commands(
  | File "c:\b\bk-windows-p38h\bazel\bazel-at-head-plus-downstream\bazelci.py", line 1384, in execute_commands
  | execute_bazel_test(
  | File "c:\b\bk-windows-p38h\bazel\bazel-at-head-plus-downstream\bazelci.py", line 2335, in execute_bazel_test
  | execute_command(
  | File "c:\b\bk-windows-p38h\bazel\bazel-at-head-plus-downstream\bazelci.py", line 2429, in execute_command
  | return subprocess.run(
  | File "C:\python3\lib\subprocess.py", line 505, in run
  | with Popen(*popenargs, **kwargs) as process:
  | File "C:\python3\lib\subprocess.py", line 951, in __init__
  | self._execute_child(args, executable, preexec_fn, close_fds,
  | File "C:\python3\lib\subprocess.py", line 1420, in _execute_child
  | hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  | FileNotFoundError: [WinError 206] The filename or extension is too long
```

CC @meteorcloudy

**Comment by meteorcloudy** [comment]
The ubuntu failures are due to test time out, the Windows failure is currently unknown, but also seen in Bazel postsubmit: https://buildkite.com/bazel/bazel-bazel/builds/23103

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazel-bazel/builds/23079#0187c76e-daf8-4230-8c8d-64876c9d8677
I guess the Windows build failed because the command line length is too long. /cc @fweikert
