### ISSUE TITLE
[Infra  Error]: "The 'info' command is only supported from within a workspace "

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/continuous-integration#1653]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3011#0188036c-44fa-4c4b-b1dd-2f08edc988c4

Platform : Multiple

Logs:
```
ERROR: The 'info' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://bazel.build/concepts/build-ref#workspace
Traceback (most recent call last):
  File "/Users/buildkite/builds/bk-imacpro-19/bazel/bazel-at-head-plus-downstream/bazelci.py", line 3953, in <module>
    sys.exit(main())
  File "/Users/buildkite/builds/bk-imacpro-19/bazel/bazel-at-head-plus-downstream/bazelci.py", line 3920, in main
    execute_commands(
  File "/Users/buildkite/builds/bk-imacpro-19/bazel/bazel-at-head-plus-downstream/bazelci.py", line 1315, in execute_commands
    os.environ["OUTPUT_BASE"] = get_output_base(bazel_binary, platform)
  File "/Users/buildkite/builds/bk-imacpro-19/bazel/bazel-at-head-plus-downstream/bazelci.py", line 2024, in get_output_base
    return execute_command_and_get_output(
  File "/Users/buildkite/builds/bk-imacpro-19/bazel/bazel-at-head-plus-downstream/bazelci.py", line 2584, in execute_command_and_get_output
    process = subprocess.run(
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'info', 'output_base']' returned non-zero exit status 2.
🚨 Error: The command exited with status 1

```

CC @fweikert

**Comment by meteorcloudy** [comment]
@fweikert I believe this is caused by https://github.com/bazelbuild/continuous-integration/commit/5e70d9d45db2bbf14bd29a794a0592b20ed52a95, where `bazel info output_base` was moved.

This is breaking because the command must run under a Bazel workspace which is specified by `working_directory` attribute in the yaml file: https://github.com/bazelbuild/examples/blob/main/.bazelci/android.yml#L6

**Comment by meteorcloudy** [comment]
Maybe we should just move `os.environ["OUTPUT_BASE"] = get_output_base(bazel_binary, platform)` into `PrepareRepoInCwd` function?

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3011#018803d6-5f5d-47ee-9b6a-05349b719e58 is probably caused by the same problem.

**Comment by meteorcloudy** [comment]
Bazel examples are green again: https://buildkite.com/bazel/bazel-bazel-examples/builds/1888
