### ISSUE TITLE
python version on ubuntu 1404 is too old

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/continuous-integration#181]
subprocess.run() does not exist. Need Python 3.5

```
[2018-02-14T11:56:11Z] bazel clean --expunge
--
  | [2018-02-14T11:56:11Z] Traceback (most recent call last):
  | [2018-02-14T11:56:11Z]   File "runner.py", line 14, in run
  | [2018-02-14T11:56:11Z]     cleanup(bazel_binary)
  | [2018-02-14T11:56:11Z]   File "runner.py", line 101, in cleanup
  | [2018-02-14T11:56:11Z]     run_command([bazel_binary, "clean", "--expunge"])
  | [2018-02-14T11:56:11Z]   File "runner.py", line 109, in run_command
  | [2018-02-14T11:56:11Z]     res = subprocess.run(args, shell)
  | [2018-02-14T11:56:11Z] AttributeError: 'module' object has no attribute 'run'
  | [2018-02-14T11:56:11Z]
  | [2018-02-14T11:56:11Z] During handling of the above exception, another exception occurred:
  | [2018-02-14T11:56:11Z]
  | [2018-02-14T11:56:11Z] Traceback (most recent call last):
  | [2018-02-14T11:56:11Z]   File "runner.py", line 127, in <module>
  | [2018-02-14T11:56:11Z]     run(configs["platforms"][args.platform], args.platform, bazel_binary, git_repository)
  | [2018-02-14T11:56:11Z]   File "runner.py", line 28, in run
  | [2018-02-14T11:56:11Z]     cleanup(bazel_binary)
  | [2018-02-14T11:56:11Z]   File "runner.py", line 101, in cleanup
  | [2018-02-14T11:56:11Z]     run_command([bazel_binary, "clean", "--expunge"])
  | [2018-02-14T11:56:11Z]   File "runner.py", line 109, in run_command
  | [2018-02-14T11:56:11Z]     res = subprocess.run(args, shell)
  | [2018-02-14T11:56:11Z] AttributeError: 'module' object has no attribute 'run'
```

**Comment by philwo** [comment]
Fixed. Python 3.6 is now available on the PATH as "python3.6".
