### ISSUE TITLE
[Bazel CI] Error creating google cloud storage client: google could not find default credentials.


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/continuous-integration#1948]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3826#018f3254-f257-41a2-8c5e-350b2a74de4f

 Platform: Ubuntu

 Logs: 
```
2024-05-01 04:43:26 ERROR  Failed to download artifact: Error creating Google Cloud Storage client: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
2024-05-01 04:43:26 FATAL  Failed to download artifacts: There were errors with downloading some of the artifacts
Traceback (most recent call last):
  File "bazelci.py", line 4434, in <module>
    sys.exit(main())
  File "bazelci.py", line 4402, in main
    execute_commands(
  File "bazelci.py", line 1272, in execute_commands
    os.environ["USE_BAZEL_VERSION"] = download_bazel_binary(tmpdir, binary_platform)
  File "bazelci.py", line 1687, in download_bazel_binary
    return download_binary(dest_dir, platform, binary_name)
  File "bazelci.py", line 1676, in download_binary
    execute_command(
  File "bazelci.py", line 2709, in execute_command
    return subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['buildkite-agent', 'artifact', 'download', 'bazel', '/tmp/tmpaoaeb44k', '--step', 'Build Bazel (:centos: CentOS 7)']' returned non-zero exit status 1.
🚨 Error: The command exited with status 1
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_dotnet
git reset eb9f34c2afe9ffd8a510fc3f8bae70a1c05bd341  --hard
export USE_BAZEL_VERSION=d474fcc64cf92f884eeb319f2ebdd58ba098e9e4 
 ``` 
 CC Greenteam @salmasamy

**Comment by Wyverald** [comment]
@fweikert This seems to happen on Windows arm64 and Linux arm64 only. Not sure what's happening there

**Comment by meteorcloudy** [comment]
We don't have GCP access on those platforms.
