### ISSUE TITLE
This version of %1 is not compatible with the version of Windows you're running for rules_dotnet


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/continuous-integration#1949]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3836#018f4c13-7caf-40e7-bb7c-97bf312b89ff

 Platform: Windows

 Logs: 
```
bazel --output_user_root=C:/b info output_base
2024/05/06 04:12:30 could not run Bazel: could not start Bazel: fork/exec C:\Users\b\AppData\Local\bazelisk\local\C--temp-tmp4swp6ij8-bazel\bin\bazel.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
Traceback (most recent call last):
  File "c:\b\bk-windows-4lt6\bazel\bazel-at-head-plus-downstream\bazelci.py", line 4434, in <module>
    sys.exit(main())
  File "c:\b\bk-windows-4lt6\bazel\bazel-at-head-plus-downstream\bazelci.py", line 4402, in main
    execute_commands(
  File "c:\b\bk-windows-4lt6\bazel\bazel-at-head-plus-downstream\bazelci.py", line 1328, in execute_commands
    PrepareRepoInCwd(True, initial_setup=True)
  File "c:\b\bk-windows-4lt6\bazel\bazel-at-head-plus-downstream\bazelci.py", line 1316, in PrepareRepoInCwd
    os.environ["OUTPUT_BASE"] = get_output_base(bazel_binary)
  File "c:\b\bk-windows-4lt6\bazel\bazel-at-head-plus-downstream\bazelci.py", line 2079, in get_output_base
    return execute_command_and_get_output(
  File "c:\b\bk-windows-4lt6\bazel\bazel-at-head-plus-downstream\bazelci.py", line 2683, in execute_command_and_get_output
    process = subprocess.run(
  File "C:\python3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root=C:/b', 'info', 'output_base']' returned non-zero exit status 1.
🚨 Error: The command exited with status 1
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_dotnet
git reset 626e28effb14f87de8375186ebb59911a16b71fb  --hard
export USE_BAZEL_VERSION=eb905bde4920954aefee0f018488d054cceaa772 
 ``` 
 CC Greenteam @mai93

**Comment by mai93** [comment]
@fweikert @meteorcloudy
