### ISSUE TITLE
[Bazel CI] [Bazel Examples ]Submodule update error with exit status 

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/continuous-integration#2100]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4245#0192f559-8a13-489d-928d-bb99cbc35cff

 Platform: Windows

Repository : Bazel Examples (tutorial-java (Java Tutorial) on :windows: Windows)

 Logs: 
```

Traceback (most recent call last):
--
  | File "c:\b\bk-windows-4lt6\bazel\bazel-at-head-plus-downstream\bazelci.py", line 4628, in <module>
  | sys.exit(main())
  | File "c:\b\bk-windows-4lt6\bazel\bazel-at-head-plus-downstream\bazelci.py", line 4566, in main
  | clone_git_repository(args.git_repository, args.git_commit)
  | File "c:\b\bk-windows-4lt6\bazel\bazel-at-head-plus-downstream\bazelci.py", line 1843, in clone_git_repository
  | execute_git_command(["git", "submodule", "foreach", "--recursive", "git reset --hard"])
  | File "c:\b\bk-windows-4lt6\bazel\bazel-at-head-plus-downstream\bazelci.py", line 1805, in execute_git_command
  | execute_command(args, print_output=not suppress_stdout, suppress_stdout=suppress_stdout)
  | File "c:\b\bk-windows-4lt6\bazel\bazel-at-head-plus-downstream\bazelci.py", line 2777, in execute_command
  | return subprocess.run(
  | File "C:\python3\lib\subprocess.py", line 528, in run
  | raise CalledProcessError(retcode, process.args,
  | subprocess.CalledProcessError: Command '['git', 'submodule', 'foreach', '--recursive', 'git reset --hard']' returned non-zero exit status 116.


``` 

 CC Greenteam @mai93

**Comment by meteorcloudy** [comment]
Retry succeded https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4245#0192fa7b-9e0d-485c-9277-853d3a98f7ad
