### ISSUE TITLE
Flakes detecting output_base

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/continuous-integration#2123]
I've noticed this in a few jobs recently
https://buildkite.com/bazel/rules-rust-rustlang/builds/12763#019369d0-adaf-48ab-aca7-067df6313621
```
bazel info output_base
2024/11/26 18:56:58 Downloading https://releases.bazel.build/7.3.2/release/bazel-7.3.2-linux-x86_64...
2024/11/26 18:57:01 could not download Bazel: failed to download bazel: failed to download bazel: could not copy from https://releases.bazel.build/7.3.2/release/bazel-7.3.2-linux-x86_64 to /var/lib/buildkite-agent/.cache/bazelisk/downloads/_tmp/download156393557: stream error: stream ID 1; INTERNAL_ERROR; received from peer
Traceback (most recent call last):
  File "bazelci.py", line 4496, in <module>
    sys.exit(main())
  File "bazelci.py", line 4464, in main
    execute_commands(
  File "bazelci.py", line 1212, in execute_commands
    PrepareRepoInCwd(True, initial_setup=True)
  File "bazelci.py", line 1200, in PrepareRepoInCwd
    os.environ["OUTPUT_BASE"] = get_output_base(bazel_binary)
  File "bazelci.py", line 1983, in get_output_base
    return execute_command_and_get_output(
  File "bazelci.py", line 2619, in execute_command_and_get_output
    process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'info', 'output_base']' returned non-zero exit status 1.
🚨 Error: The command exited with status 1
user command error: The plugin docker command hook exited with status 1
```

**Comment by UebelAndre** [comment]
I'm still hitting this one a lot in rules_rust pull-requests.
