### ISSUE TITLE
rules_k8s fails due to missing pip package

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/continuous-integration#213]
setuptools seems to be missing for python 2

```
[2018-02-22T09:49:54Z] ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@examples_helloworld_pip//': pip_import failed:  (Traceback (most recent call last):
--
  | [2018-02-22T09:49:54Z]   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
  | [2018-02-22T09:49:54Z]     "__main__", fname, loader, pkg_name)
  | [2018-02-22T09:49:54Z]   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
  | [2018-02-22T09:49:54Z]     exec code in run_globals
  | [2018-02-22T09:49:54Z]   File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/740b811a6adb3ca3b7c83199bf22acd0/external/io_bazel_rules_python/tools/piptool.par/__main__.py", line 66, in <module>
  | [2018-02-22T09:49:54Z]   File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/740b811a6adb3ca3b7c83199bf22acd0/external/io_bazel_rules_python/tools/piptool.par/__main__.py", line 51, in extract_packages
  | [2018-02-22T09:49:54Z]   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 935, in resource_filename
  | [2018-02-22T09:49:54Z]     return get_provider(package_or_requirement).get_resource_filename(
  | [2018-02-22T09:49:54Z]   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 223, in get_provider
  | [2018-02-22T09:49:54Z]     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  | [2018-02-22T09:49:54Z]   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
  | [2018-02-22T09:49:54Z]     needed = self.resolve(parse_requirements(requirements))
  | [2018-02-22T09:49:54Z]   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
  | [2018-02-22T09:49:54Z]     raise DistributionNotFound(req)
  | [2018-02-22T09:49:54Z] pkg_resources.DistributionNotFound: setuptools
  | [2018-02-22T09:49:54Z] )
  | [2018-02-22T09:49:54Z]
  | [2018-02-22T09:49:54Z]
```

**Comment by philwo** [comment]
Fixed.

**Comment by buchgr** [comment]
<3
