### ISSUE TITLE
xcode-locator": error=13, Permission denied

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/continuous-integration#215]
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
..F...
======================================================================
FAIL: testLinkSharedLibrary (__main__.CcImportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_ci/b6a4a4fe7115e826c0cb7a3daac9979b/bazel-sandbox/1207373264154890033/execroot/io_bazel/bazel-out/darwin-fastbuild/bin/src/test/py/bazel/cc_import_test.runfiles/io_bazel/src/test/py/bazel/cc_import_test.py", line 169, in testLinkSharedLibrary
    self.AssertExitCode(exit_code, 0, stderr)
  File "/private/var/tmp/_bazel_ci/b6a4a4fe7115e826c0cb7a3daac9979b/bazel-sandbox/1207373264154890033/execroot/io_bazel/bazel-out/darwin-fastbuild/bin/src/test/py/bazel/cc_import_test.runfiles/io_bazel/src/test/py/bazel/test_base.py", line 67, in AssertExitCode
    '(end stderr)------------------------------------------',
AssertionError: Bazel exited with 1 (expected 0), stderr:
(start stderr)----------------------------------------
INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_ci/b6a4a4fe7115e826c0cb7a3daac9979b/bazel-sandbox/1207373264154890033/execroot/io_bazel/_tmp/ea16989bb00e433b5db4334c74447989' and max_idle_secs default is '15'.
Loading:
Loading: 0 packages loaded
Analyzing: target //main:B (4 packages loaded)
Analyzing: target //main:B (4 packages loaded)
INFO: Analysed target //main:B (6 packages loaded).
INFO: Found 1 target...
[0 / 8] [-----] BazelWorkspaceStatusAction stable-status.txt
ERROR: /private/var/tmp/_bazel_ci/b6a4a4fe7115e826c0cb7a3daac9979b/bazel-sandbox/1207373264154890033/execroot/io_bazel/_tmp/ea16989bb00e433b5db4334c74447989/tests_root/tmp4utpzY/main/BUILD:1:1: C++ compilation of rule '//main:B' failed: I/O exception during sandboxed execution: com.google.devtools.build.lib.shell.ExecFailedException: java.io.IOException: Cannot run program "/private/var/tmp/_bazel_ci/b6a4a4fe7115e826c0cb7a3daac9979b/bazel-sandbox/1207373264154890033/execroot/io_bazel/_tmp/ea16989bb00e433b5db4334c74447989/_bazel_ci/1755c5c016e5e6516064ac894616aef7/execroot/__main__/_bin/xcode-locator": error=13, Permission denied
Target //main:B failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.207s, Critical Path: 0.03s
FAILED: Build did NOT complete successfully
(end stderr)------------------------------------------

----------------------------------------------------------------------
Ran 6 tests in 234.182s

FAILED (failures=1)
```

On macOS we occassionally get this error. any thoughts @mhlopko @philwo ?

**Comment by mhlopko** [comment]
@c-parsons

**Comment by buchgr** [comment]
```
ERROR: /private/var/tmp/_bazel_ci/20c493295d66f225cd5d559064480deb/bazel-sandbox/3757063718277136875/execroot/io_bazel/_tmp/ea16989bb00e433b5db4334c74447989/tests_root/tmp9mgnG6/lib/BUILD:15:1: 
C++ compilation of rule '//lib:libA' failed: 
I/O exception during sandboxed execution: com.google.devtools.build.lib.shell.ExecFailedException: java.io.IOException: Cannot run program "/private/var/tmp/_bazel_ci/20c493295d66f225cd5d559064480deb/bazel-sandbox/3757063718277136875/execroot/io_bazel/_tmp/ea16989bb00e433b5db4334c74447989/_bazel_ci/edeb601d24e8b251d96f241e5e70a3e6/execroot/__main__/_bin/xcode-locator": error=13, Permission denied
```
https://buildkite.com/bazel/bazel-bazel-postsubmit/builds/281#126e6bcd-91bd-45e4-8aeb-736c05858fb9

**Comment by philwo** [comment]
I haven't seen this in months, closing.
