### ISSUE TITLE
Global Presubmits can't download the bazel under test

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#253]
Looks like almost every test under this run failed:
https://buildkite.com/bazel/google-bazel-global-presubmit/builds/2

Errors look like this:
```
buildkite-agent artifact download bazel-bin/src/bazel /tmp/tmp1gy5wf79 --step Build Bazel (:ubuntu: 16.04)
--
  | 2018-03-21 20:39:20 INFO   Searching for artifacts: "bazel-bin/src/bazel" within step: "Build Bazel (:ubuntu: 16.04)"
  | 2018-03-21 20:39:21 FATAL  Failed to download artifacts: GET https://agent.buildkite.com/v3/builds/5bfc2655-1784-4bf6-b7f1-b48996b0b3d7/artifacts/search?query=bazel-bin%2Fsrc%2Fbazel&scope=Build+Bazel+%28%3Aubuntu%3A+16.04%29: 404 A step could not be found matching: `Build Bazel (:ubuntu: 16.04)`
```

Or this:
```
Traceback (most recent call last):
--
  | File "bazelci.py", line 1172, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 1159, in main
  | args.build_only, args.test_only)
  | File "bazelci.py", line 352, in execute_commands
  | bazel_binary = download_bazel_binary(tmpdir, platform)
  | File "bazelci.py", line 570, in download_bazel_binary
  | binary_path, dest_dir, "--step", source_step])
  | File "bazelci.py", line 786, in execute_command
  | return subprocess.run(args, shell=shell, check=fail_if_nonzero).returncode
  | File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['buildkite-agent', 'artifact', 'download', 'bazel-bin/src/bazel', '/tmp/tmpumtb2cqo', '--step', 'Build Bazel (:ubuntu: 14.04)']' returned non-zero exit status 1.
```

**Comment by philwo** [comment]
@buchgr Could it be that we're no longer uploading the bazel artifacts after the split into the downstream pipeline and the "publish nightly release" pipeline?

**Comment by katre** [comment]
The daily global postsubmit is showing the same errors: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/171

**Comment by katre** [comment]
I would really really like to run a global presubmit for https://bazel-review.googlesource.com/c/bazel/+/46430 before I submit it (to avoid having to roll it back after everything fails). Any chance this is a simple fix?

**Comment by philwo** [comment]
Looking now.

**Comment by katre** [comment]
Haven't seen this recently. Re-open if needed.
