### ISSUE TITLE
Install missing pip package for TF build

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#264]
To address the following breakage:
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/196#8e7b45c0-48a2-4355-90ae-f6985f63ec94

```

ERROR: /var/lib/buildkite-agent/builds/buildkite-ubuntu1404-t7fq-1/bazel-downstream-projects/tensorflow/tensorflow/tools/api/generator/BUILD:27:1: Couldn't build file tensorflow/tools/api/generator/api/__init__.py: Executing genrule //tensorflow/tools/api/generator:python_api_gen failed (Exit 1)
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9ea361306e87aecb7af4c4d253d6d52a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/tools/api/generator/create_python_api.py", line 26, in <module>
  | from tensorflow.python.util import tf_decorator
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9ea361306e87aecb7af4c4d253d6d52a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
  | from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9ea361306e87aecb7af4c4d253d6d52a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 104, in <module>
  | from tensorflow.python.framework.importer import import_graph_def
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9ea361306e87aecb7af4c4d253d6d52a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 32, in <module>
  | from tensorflow.python.framework import function
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9ea361306e87aecb7af4c4d253d6d52a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 37, in <module>
  | from tensorflow.python.ops import variable_scope as vs
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9ea361306e87aecb7af4c4d253d6d52a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 24, in <module>
  | import enum  # pylint: disable=g-bad-import-order
  | ImportError: No module named enum

```
@philwo

**Comment by meteorcloudy** [comment]
More possible missing package: `mock` 
Found it missing when building locally
