### ISSUE TITLE
Windows slaves are disconnecting during bazel-tests

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#42]
bazel-tests for Windows with the latest Bazel are failing due to the slave disconnecting from the Jenkins master during tests.

Logs: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/lastFailedBuild/console

```
c:\jenkins\workspace\bazel-tests\BAZEL_VERSION\HEAD\PLATFORM_NAME\windows-x86_64>c:\bazel_ci\installs\HEAD\bazel.exe --bazelrc=c:\jenkins\workspace\bazel-tests\BAZEL_VERSION\HEAD\PLATFORM_NAME\windows-x86_64\.bazelrc test //src/test/java/... + //src/test/shell/bazel:bazel_windows_example_test 
ERROR: Skipping '+': Bad target pattern '+': package names may contain only A-Z, a-z, 0-9, '/', '-', '.' and '_'.
____Loading package: src/test/java/com/google/devtools/build/android
ERROR: Skipping '+': Bad target pattern '+': package names may contain only A-Z, a-z, 0-9, '/', '-', '.' and '_'.
____Loading package: @bazel_tools//tools/cpp
____Loading package: @local_config_xcode//
____Loading package: @local_jdk//
Slave went offline during the build
ERROR: Connection was broken: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@1d8b1df6[name=windows-x86_64-4]
	at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:208)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:628)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:136)
	at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:306)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:561)
	... 6 more
```

**Comment by katre** [comment]
Logs on the windows worker are full of errors like this:
```
Dec 14, 2016 3:46:28 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins:50000
Dec 14, 2016 3:46:28 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP-connect
Dec 14, 2016 3:46:28 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server didn't accept the handshake: windows-x86_64-4 is already connected to this master. Rejecting this connection.
Dec 14, 2016 3:46:28 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins:50000
Dec 14, 2016 3:46:28 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:286)
	at hudson.remoting.Engine.run(Engine.java:262)

Dec 14, 2016 3:46:29 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: windows-x86_64-4
Dec 14, 2016 3:46:29 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Dec 14, 2016 3:46:29 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://jenkins/, http://jenkins/]
Dec 14, 2016 3:46:29 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Dec 14, 2016 3:46:29 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins:50000
Dec 14, 2016 3:46:29 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP2-connect
Dec 14, 2016 3:46:29 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connected
```

**Comment by katre** [comment]
Tests are passing now, this may have been spurious. Closing for now, will re-open if it re-occurs.
