### ISSUE TITLE
CI is reporting build success when it was not successful

### ISSUE THREAD

**Issue by achew22** [bazelbuild/continuous-integration#449]
Looking at the tests associated with https://github.com/bazelbuild/bazel-watcher/pull/144 buildkite reports success, but if you expand the logs, they each have [the following error](https://buildkite.com/bazel/bazel-watcher/builds/364#7fef6446-cb52-4cb3-8e97-2877a58f7301).

```
ERROR: /workdir/e2e/profiler/BUILD:6:1: Traceback (most recent call last):
  | File "/workdir/e2e/profiler/BUILD", line 6
  | bazel_go_integration_test(name = "go_default_test", srcs = [..."], <4 more arguments>)
  | File "/workdir/e2e/profiler/BUILD", line 13, in bazel_go_integration_test
  | GET_LATEST_BAZEL_VERSIONS()
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 62, in GET_LATEST_BAZEL_VERSIONS
  | toReturn.append(_unfill(v))
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 62, in toReturn.append
  | _unfill(v)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 29, in _unfill
  | range((len(v) / l))
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 29, in range
  | len(v) / l
  | The `/` operator has been removed. Please use the `//` operator for integer division. You can temporarily enable the `/` operator by passing the flag --incompatible_disallow_slash_operator=false
  | ERROR: package contains errors: e2e/profiler
  | ERROR: /workdir/e2e/simple/BUILD:6:1: Traceback (most recent call last):
  | File "/workdir/e2e/simple/BUILD", line 6
  | bazel_go_integration_test(name = "go_default_test", srcs = [..."], <4 more arguments>)
  | File "/workdir/e2e/simple/BUILD", line 13, in bazel_go_integration_test
  | GET_LATEST_BAZEL_VERSIONS()
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 62, in GET_LATEST_BAZEL_VERSIONS
  | toReturn.append(_unfill(v))
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 62, in toReturn.append
  | _unfill(v)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 29, in _unfill
  | range((len(v) / l))
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 29, in range
  | len(v) / l
  | The `/` operator has been removed. Please use the `//` operator for integer division. You can temporarily enable the `/` operator by passing the flag --incompatible_disallow_slash_operator=false
  | ERROR: package contains errors: e2e/simple
  | ERROR: /workdir/e2e/output_runner/BUILD:4:1: Traceback (most recent call last):
  | File "/workdir/e2e/output_runner/BUILD", line 4
  | bazel_go_integration_test(name = "go_default_test", srcs = [..."], <4 more arguments>)
  | File "/workdir/e2e/output_runner/BUILD", line 11, in bazel_go_integration_test
  | GET_LATEST_BAZEL_VERSIONS()
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 62, in GET_LATEST_BAZEL_VERSIONS
  | toReturn.append(_unfill(v))
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 62, in toReturn.append
  | _unfill(v)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 29, in _unfill
  | range((len(v) / l))
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 29, in range
  | len(v) / l
  | The `/` operator has been removed. Please use the `//` operator for integer division. You can temporarily enable the `/` operator by passing the flag --incompatible_disallow_slash_operator=false
  | ERROR: package contains errors: e2e/output_runner
  | ERROR: /workdir/e2e/live_reload/BUILD:6:1: Traceback (most recent call last):
  | File "/workdir/e2e/live_reload/BUILD", line 6
  | bazel_go_integration_test(name = "go_default_test", srcs = [..."], <4 more arguments>)
  | File "/workdir/e2e/live_reload/BUILD", line 13, in bazel_go_integration_test
  | GET_LATEST_BAZEL_VERSIONS()
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 62, in GET_LATEST_BAZEL_VERSIONS
  | toReturn.append(_unfill(v))
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 62, in toReturn.append
  | _unfill(v)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 29, in _unfill
  | range((len(v) / l))
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_bazelbuild_bazel_integration_testing/tools/common.bzl", line 29, in range
  | len(v) / l
  | The `/` operator has been removed. Please use the `//` operator for integer division. You can temporarily enable the `/` operator by passing the flag --incompatible_disallow_slash_operator=false
```

**Comment by meteorcloudy** [comment]
This is more like a Bazel issue, it didn't report this as an error.
/cc @c-parsons 

In the mean time, we should fix bazel-watcher according to the migration plan of this incompatible change at https://github.com/bazelbuild/bazel/issues/5823#issuecomment-437485026
