### ISSUE TITLE
Gerrit builds failing due to missing Node.js

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#49]
Gerrit's //:release target depends on being able to fetch dependencies via Node.js. As Node.js is not installed on the linux or darwin slaves, these builds are failing.

For some reason, darwin builds are visibly failing, while linux builds are succeeding, but trying to build //:elease while logged into the slave fails.

Sample error, darwin:
```
ERROR: /Users/ci/workspace/gerrit/BAZEL_VERSION/HEAD/PLATFORM_NAME/darwin-x86_64/polygerrit-ui/app/BUILD:14:1: error executing shell command: 'export PATH && p=$PWD && rm -rf bazel-out/local-fastbuild/bin/polygerrit-ui/app/gr-app.html.dir && mkdir -p bazel-out/local-fastbuild/bin/polygerrit-ui/app/gr-app.html.dir/polygerrit-ui/app/bower_c...' failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
env: node: No such file or directory
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_ci/ecb628661259d45b1bcf8030dc6f079b/execroot/darwin-x86_64/tools/js/run_npm_binary.py", line 91, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/private/var/tmp/_bazel_ci/ecb628661259d45b1bcf8030dc6f079b/execroot/darwin-x86_64/tools/js/run_npm_binary.py", line 87, in main
    subprocess.check_call([bin] + args[1:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/private/var/tmp/_bazel_ci/ecb628661259d45b1bcf8030dc6f079b/execroot/darwin-x86_64/external/vulcanize/vulcanize@1.14.8-679107f251c19ab7539529b1e3fdd40829e6fc63/package/bin/vulcanize', '--inline-scripts', '--inline-css', '--strip-comments', '--out-html', '/private/var/tmp/_bazel_ci/ecb628661259d45b1bcf8030dc6f079b/execroot/darwin-x86_64/bazel-out/local-fastbuild/genfiles/polygerrit-ui/app/gr-app.html.vulcanized.html', 'polygerrit-ui/app/elements/gr-app.html']' returned non-zero exit status 127
WARNING: Cannot delete sandbox directory after action execution: /private/var/tmp/_bazel_ci/ecb628661259d45b1bcf8030dc6f079b/bazel-sandbox/3f26a0c9-aaae-4185-96fd-f71b509aa255-1 (java.io.IOException: /private/var/tmp/_bazel_ci/ecb628661259d45b1bcf8030dc6f079b/bazel-sandbox/3f26a0c9-aaae-4185-96fd-f71b509aa255-1/execroot/darwin-x86_64/bazel-out/local-fastbuild/genfiles/gerrit-server/src/main/prolog/java_6727346770098220526/gerrit (Directory not empty)).
Target //:release failed to build
```

**Comment by katre** [comment]
We should either install Node.js on darwin and linux slaves, or stop trying to build the Gerrit //:release target.

**Comment by katre** [comment]
Note: all actual tests still pass, it's only building //:release that fails.

**Comment by damienmg** [comment]
This will be fixed with the new pipeline.
