### ISSUE TITLE
"Try Update Last Green Commit" fails with stack trace

### ISSUE THREAD

**Issue by philwo** [bazelbuild/continuous-integration#552]
The "Try Update Last Green Commit fails" fails for every build:

```
$ /bin/sh -e -c 'curl -sS https://raw.githubusercontent.com/bazelbuild/continuous-integration/master/buildkite/bazelci.py?1552013933 -o bazelci.py
--
  | python3.6 bazelci.py try_update_last_green_commit'
  | Traceback (most recent call last):
  | File "bazelci.py", line 2296, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 2285, in main
  | try_update_last_green_commit()
  | File "bazelci.py", line 1977, in try_update_last_green_commit
  | failing_jobs = [j["name"] for j in build_info["jobs"] if HasFailed(j)]
  | File "bazelci.py", line 1977, in <listcomp>
  | failing_jobs = [j["name"] for j in build_info["jobs"] if HasFailed(j)]
  | File "bazelci.py", line 1972, in HasFailed
  | job["state"] != "passed"
  | KeyError: 'state'
  | 🚨 Error: The command exited with status 1
```

Example: https://buildkite.com/bazel/bazel-bazel/builds/7113#932ffa2d-a35b-466f-b9d6-ec13f20eb5de

**Comment by hlopko** [comment]
cc @hlopko
