### ISSUE TITLE
Bazel CI, Bazelisk + Incompatible flags: last pipeline step failed

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/continuous-integration#586]
"Aggregate incompatible flags test result" step failed:
```

2019-03-27 07:54:42 FATAL  Failed to annotate build: POST https://agent.buildkite.com/v3/jobs/2da0d1cf-a351-4cc9-8a7e-53b8b3f51de1/annotations: 400 The annotation body must be less than 100 KB
--
  | Traceback (most recent call last):
  | File "aggregate_incompatible_flags_test_result.py", line 236, in <module>
  | sys.exit(main())
  | File "aggregate_incompatible_flags_test_result.py", line 224, in main
  | print_result_info(args.build_number, client)
  | File "aggregate_incompatible_flags_test_result.py", line 202, in print_result_info
  | print_flags_need_to_migrate(failed_jobs_per_flag)
  | File "aggregate_incompatible_flags_test_result.py", line 138, in print_flags_need_to_migrate
  | print_info("flags_need_to_migrate", "error", info_text)
  | File "aggregate_incompatible_flags_test_result.py", line 177, in print_info
  | f"\n{info_str}\n",
  | File "/workdir/bazelci.py", line 1369, in execute_command
  | return subprocess.run(args, shell=shell, check=fail_if_nonzero, env=os.environ).returncode
  | File "/usr/lib/python3.6/subprocess.py", line 418, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['buildkite-agent', 'annotate', '--append', '--context=flags_need_to_migrate', '--style=error', '\n#### Downstream projects need to migrate for the following flags\n* **--incompatible_disallow_struct_provider_syntax** <a href="https://github.com/bazelbuild/bazel/issues/7347" target="_blank">:github:</a>\n  - **Android Studio Plugin**: <a
(...)
a4bb-f905c4b2822a" target="_blank">:windows: (JDK 8)</a>\n']' returned non-zero exit status 1.
```

https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/57#2da0d1cf-a351-4cc9-8a7e-53b8b3f51de1

**Comment by laszlocsomor** [comment]
@fweikert @meteorcloudy

**Comment by laszlocsomor** [comment]
Thanks for the quick fix!
How will BuildKite pick this up?

**Comment by laszlocsomor** [comment]
I reran the failed job and it passed! \o/
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/57#job-bc144aea-5307-4f65-ab8b-89553d11cc22
