### ISSUE TITLE
bazelisk-plus-incompatible-flags incorrectly reports a flag as needing migration

### ISSUE THREAD

**Issue by cushon** [bazelbuild/continuous-integration#590]
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/58 says that `--incompatible_use_toolchain_providers_in_java_common` needs migration for the 'IntelliJ Plugin Aspect', but when I click through to the build I don't see any errors: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/58#4c5e6281-604e-47ab-875d-d2eec32e8cfe

```
bazel build --show_progress_rate_limit=5 --curses=yes --color=yes --verbose_failures --keep_going --jobs=32 --announce_rc --experimental_multi_threaded_digest --sandbox_tmpfs_path=/tmp --remote_timeout=60 --disk_cache= --remote_max_connections=200 --host_platform_remote_properties_override=properties:{name:"platform" value:"ubuntu1604"} --google_default_credentials --remote_http_cache=https://storage.googleapis.com/bazel-untrusted-buildkite-cache //aspect:aspect_files --incompatible_use_toolchain_providers_in_java_common
  | INFO: Invocation ID: 8e9201e7-bbcc-4be9-97df-871714f5d25c
  | INFO: Options provided by the client:
  | Inherited 'common' options: --isatty=1 --terminal_columns=0
  | INFO: Build option --incompatible_use_jdk11_as_host_javabase has changed, discarding analysis cache.
  | INFO: Analysed target //aspect:aspect_files (24 packages loaded, 691 targets configured).
  | INFO: Found 1 target...
  | Target //aspect:aspect_files up-to-date:
  | bazel-genfiles/aspect/intellij_info_bundled.bzl
  | bazel-genfiles/aspect/BUILD.bazel
  | bazel-bin/aspect/tools/JarFilter_deploy.jar
  | bazel-bin/aspect/tools/PackageParser_deploy.jar
  | INFO: Elapsed time: 1.478s, Critical Path: 1.05s
  | INFO: 5 processes: 5 remote cache hit.
  | INFO: Build completed successfully, 6 total actions
```

Am I mis-reading what the UI is telling me, or is there a bug in the way it's processing the build output?

**Comment by meteorcloudy** [comment]
It's in the test section:
```
bazel test --flaky_test_attempts=3 --build_tests_only --local_test_jobs=12 --show_progress_rate_limit=5 --curses=yes --color=yes --verbose_failures --keep_going --jobs=32 --announce_rc --experimental_multi_threaded_digest --sandbox_tmpfs_path=/tmp --experimental_build_event_json_file_path_conversion=false --build_event_json_file=/tmp/tmpfzmk40dm/test_bep.json --remote_timeout=60 --disk_cache= --remote_max_connections=200 --host_platform_remote_properties_override=properties:{name:"platform" value:"ubuntu1604"} --google_default_credentials --remote_http_cache=https://storage.googleapis.com/bazel-untrusted-buildkite-cache --test_output=errors --test_env=HOME --sandbox_writable_path=/home/bazel/.cache/bazelisk //aspect/testing/... --incompatible_use_toolchain_providers_in_java_common
--
  | INFO: Invocation ID: 43da83af-fca2-40d3-aa05-379d7be4dbb8
  | INFO: Options provided by the client:
  | Inherited 'common' options: --isatty=1 --terminal_columns=0
  | INFO: Build option --incompatible_use_jdk11_as_host_javabase has changed, discarding analysis cache.
  | ERROR: /home/bazel/.cache/bazel/_bazel_bazel/03f43b08bfdcb2bd3eaf10586ed8014e/external/io_bazel_rules_scala/third_party/dependency_analyzer/src/main/BUILD:5:1: in scala_library_for_plugin_bootstrapping rule @io_bazel_rules_scala//third_party/dependency_analyzer/src/main:dependency_analyzer:
  | Traceback (most recent call last):
  | File "/home/bazel/.cache/bazel/_bazel_bazel/03f43b08bfdcb2bd3eaf10586ed8014e/external/io_bazel_rules_scala/third_party/dependency_analyzer/src/main/BUILD", line 5
  | scala_library_for_plugin_bootstrapping(name = 'dependency_analyzer')
  | File "/home/bazel/.cache/bazel/_bazel_bazel/03f43b08bfdcb2bd3eaf10586ed8014e/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 753, in scala_library_for_plugin_bootstrapping_impl
  | _lib(ctx, scalac_provider.default_class..., <3 more arguments>)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/03f43b08bfdcb2bd3eaf10586ed8014e/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 676, in _lib
  | _compile_or_empty(ctx, ctx.outputs.manifest, cjars, srcj..., <6 more arguments>)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/03f43b08bfdcb2bd3eaf10586ed8014e/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 461, in _compile_or_empty
  | java_common.run_ijar(ctx.actions, jar = ctx.outputs.jar, <2 more arguments>)
  | ConfiguredTarget(@bazel_tools//tools/jdk:current_java_toolchain, 1d59a9afc1d06e82cdbe0b184ac27641) pass a java_common.JavaToolchainInfo instead of a configured target; see https://github.com/bazelbuild/bazel/issues/7186.
  | ERROR: /home/bazel/.cache/bazel/_bazel_bazel/03f43b08bfdcb2bd3eaf10586ed8014e/external/io_bazel_rules_scala/third_party/unused_dependency_checker/src/main/BUILD:5:1: in scala_library_for_plugin_bootstrapping rule @io_bazel_rules_scala//third_party/unused_dependency_checker/src/main:unused_dependency_checker:
  | Traceback (most recent call last):
  | File "/home/bazel/.cache/bazel/_bazel_bazel/03f43b08bfdcb2bd3eaf10586ed8014e/external/io_bazel_rules_scala/third_party/unused_dependency_checker/src/main/BUILD", line 5
  | scala_library_for_plugin_bootstrapping(name = 'unused_dependency_checker')
  | File "/home/bazel/.cache/bazel/_bazel_bazel/03f43b08bfdcb2bd3eaf10586ed8014e/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 753, in scala_library_for_plugin_bootstrapping_impl
  | _lib(ctx, scalac_provider.default_class..., <3 more arguments>)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/03f43b08bfdcb2bd3eaf10586ed8014e/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 676, in _lib
  | _compile_or_empty(ctx, ctx.outputs.manifest, cjars, srcj..., <6 more arguments>)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/03f43b08bfdcb2bd3eaf10586ed8014e/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 461, in _compile_or_empty
  | java_common.run_ijar(ctx.actions, jar = ctx.outputs.jar, <2 more arguments>)
  | ConfiguredTarget(@bazel_tools//tools/jdk:current_java_toolchain, 1d59a9afc1d06e82cdbe0b184ac27641) pass a java_common.JavaToolchainInfo instead of a configured target; see https://github.com/bazelbuild/bazel/issues/7186.


```
