### ISSUE TITLE
Bootstrapping distribution file failed: IllegalArgumentException in jar

### ISSUE THREAD

**Issue by serynth** [bazelbuild/continuous-integration#626]
https://buildkite.com/bazel/google-bazel-presubmit/builds/18535#eab4c50d-410d-4dd3-b8b1-2f7471a12723

```
** test_bootstrap **************************************************************
Building Bazel from scratch..../usr/lib/jvm/zulu-9-amd64/bin/jar cmf /tmp/bazel_xuPJx0Tq/MANIFEST.MF /tmp/bazel_xuPJx0Tq/libblaze.jar -C /tmp/bazel_xuPJx0Tq/classes A.class -C /tmp/bazel_xuPJx0Tq/classes AUTHORS -C /tmp/bazel_xuPJx0Tq/classes AnnotatedClass.class -C /tmp/bazel_xuPJx0Tq/classes Annotations$ParametersOnlyAnnotation.class -C /tmp/bazel_xuPJx0Tq/classes Annotations$RuntimeInvisible.class -C /tmp/bazel_xuPJx0Tq/classes Annotations$RuntimeVisible.class -C /tmp/bazel_xuPJx0Tq/classes Annotations.class -C /tmp/bazel_xuPJx0Tq/classes B.class -C /tmp/bazel_xuPJx0Tq/classes LICENSE -C /tmp/bazel_xuPJx0Tq/classes LICENSE-junit.txt -C /tmp/bazel_xuPJx0Tq/classes LICENSE.txt -C /tmp/bazel_xuPJx0Tq/classes NOTICE -C /tmp/bazel_xuPJx0Tq/classes NestTest$P.class -C /tmp/bazel_xuPJx0Tq/classes NestTest.class -C /tmp/bazel_xuPJx0Tq/classes about.html -C /tmp/bazel_xuPJx0Tq/classes android -C /tmp/bazel_xuPJx0Tq/classes api_diff.proto -C /tmp/bazel_xuPJx0Tq/classes autovalue -C /tmp/bazel_xuPJx0Tq/classes blogspot -C /tmp/bazel_xuPJx0Tq/classes build -C /tmp/bazel_xuPJx0Tq/classes com -C /tmp/bazel_xuPJx0Tq/classes deps.proto -C /tmp/bazel_xuPJx0Tq/classes difflib -C /tmp/bazel_xuPJx0Tq/classes io -C /tmp/bazel_xuPJx0Tq/classes jacocoagent.jar -C /tmp/bazel_xuPJx0Tq/classes javax -C /tmp/bazel_xuPJx0Tq/classes jdk -C /tmp/bazel_xuPJx0Tq/classes junit -C /tmp/bazel_xuPJx0Tq/classes licenses -C /tmp/bazel_xuPJx0Tq/classes lombok -C /tmp/bazel_xuPJx0Tq/classes module-info.class -C /tmp/bazel_xuPJx0Tq/classes module-info.java -C /tmp/bazel_xuPJx0Tq/classes mozilla -C /tmp/bazel_xuPJx0Tq/classes net -C /tmp/bazel_xuPJx0Tq/classes org -C /tmp/bazel_xuPJx0Tq/classes pom.xml -C /tmp/bazel_xuPJx0Tq/classes proguard -C /tmp/bazel_xuPJx0Tq/classes sun -C /tmp/bazel_xuPJx0Tq/classes textfile.txt
java.lang.IllegalArgumentException
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:182)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:453)
	at java.base/jdk.internal.module.ModuleInfoExtender.toByteArray(ModuleInfoExtender.java:194)
	at java.base/jdk.internal.module.ModuleInfoExtender.write(ModuleInfoExtender.java:179)
	at jdk.jartool/sun.tools.jar.Main.extendedInfoBytes(Main.java:2137)
	at jdk.jartool/sun.tools.jar.Main.addExtendedModuleAttributes(Main.java:2068)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:294)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1670)
```

I couldn't reproduce this on my machine... And I'm not sure how my change could have done this?

**Comment by philwo** [comment]
Sync and retry - it's "fixed" at head by disabling the JDK9 platform :)
