### ISSUE TITLE
BUILD file generator broken on CI, passing locally

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/continuous-integration#630]
Locally:
```
# git clone https://github.com/bazelbuild/BUILD_file_generator.git
# cd BUILD_file_generator && git checkout fcbb46fe319aa78fab92c8cca373b7ad588f56f5
# bazel test --test_env=HOME //lang/java/src/test/java/com/google/devtools/build/bfg:JavaSourceFileParserTest
(all good)
```

Using Docker:
```
# docker run -it gcr.io/bazel-untrusted/ubuntu1804:java11 /bin/bash
...
# mkdir ~/docker-user && cd ~/docker-user
# git clone https://github.com/bazelbuild/BUILD_file_generator.git
# cd BUILD_file_generator && git checkout fcbb46fe319aa78fab92c8cca373b7ad588f56f5
# bazel test --test_env=HOME //lang/java/src/test/java/com/google/devtools/build/bfg:JavaSourceFileParserTest
(fails)
```

I can repro at https://github.com/bazelbuild/BUILD_file_generator/commit/fcbb46fe319aa78fab92c8cca373b7ad588f56f5 and at its parent commits (https://github.com/bazelbuild/BUILD_file_generator/commit/8702ea101535719dc6fb3c9bdf6bab6893f54771 and https://github.com/bazelbuild/BUILD_file_generator/commit/9fd311171a2d94432ab4be596d3c67e1db0b3c88). Both Bazels are 0.24.1

**Comment by laszlocsomor** [comment]
Error log:
```
INFO: From Testing //lang/java/src/test/java/com/google/devtools/build/bfg:JavaSourceFileParserTest:           
==================== Test output for //lang/java/src/test/java/com/google/devtools/build/bfg:JavaSourceFileParserTest:
JUnit4 Test Runner
..........E
Time: 1.514
There was 1 failure:
1) ruleKindDetection(com.google.devtools.build.bfg.JavaSourceFileParserTest)                                   
java.lang.AssertionError: Not true that <[/src/x/Binary.java=java_library, /src/x/SomeTest.java=java_test, /src/x/AbstractTest.java=java_library]> contains exactly <[/src/x/Binary.java=java_binary, /src/x/SomeTest.java=java_test, /src/x/AbstractTest.java=java_library]>. It is missing <[/src/x/Binary.java=java_binary]> and has unexpected items <[/src/x/Binary.java=java_library]>
        at com.google.devtools.build.bfg.JavaSourceFileParserTest.ruleKindDetection(JavaSourceFileParserTest.java:323)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                      
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)    
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                          
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)                
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)                 
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)                  
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)                   
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)                       
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)                                       
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)                   
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)                   
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)                                         
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)                                     
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)                                   
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)                                     
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)                                    
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)                                           
        at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)                                                  
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)                                                  
        at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)                      
        at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:153)           
        at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:84)                       

FAILURES!!!
Tests run: 10,  Failures: 1
```

**Comment by philwo** [comment]
The project seems to be incompatible with OpenJDK 11. That is tracked here: https://github.com/bazelbuild/BUILD_file_generator/issues/53

Closing this issue, because it's not CI's fault.
