### ISSUE TITLE
Error building //gcr:deploy

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/continuous-integration#72]
```
$ sudo JAVA_HOME=/usr/local/buildtools/java/jdk8 bazel run //gcr:deploy
.........
INFO: Found 1 target...
Slow read: a 922029568-byte read from /root/.cache/bazel/_bazel_root/4927d7c2141a0983d1e0cec739c53faf/external/ubuntu-wily-amd64-ssh/base.tar took 6285ms.
Slow read: a 1268174336-byte read from /root/.cache/bazel/_bazel_root/4927d7c2141a0983d1e0cec739c53faf/external/ubuntu-wily-amd64-deploy/base.tar took 8667ms.
ERROR: /home/kchodorow/gitroot/continuous-integration/jenkins/jobs/BUILD:62:1: null failed: Process exited with status 1 [sandboxed].
Traceback (most recent call last):
  File "bazel-out/host/bin/templating/template_engine", line 142, in <module>
    Main()
  File "bazel-out/host/bin/templating/template_engine", line 116, in Main
    'Cannot exec() %r: file not found.' % main_filename
AssertionError: Cannot exec() '/root/.cache/bazel/_bazel_root/4927d7c2141a0983d1e0cec739c53faf/bazel-sandbox/0beffe7e-83c2-4aac-a216-efe929e889f1-46/execroot/continuous-integration/bazel-out/host/bin/templating/template_engine.runfiles/io_bazel_ci/templating/main.py': file not found.
Use --strategy=Generating=standalone to disable sandboxing for the failing actions.
Target //gcr:deploy failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 409.461s, Critical Path: 21.18s
ERROR: Build failed. Not running target.
```

**Comment by damienmg** [comment]
Bazel should not be run as root. The documentation was updated to explain to be in the docker group.
