### ISSUE TITLE
Slaves are all offlines

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/continuous-integration#86]
/cc @laszlocsomor @meteorcloudy @steren let's continue the discussion here.

For reference hangouts with @meteorcloudy:

> Yun Peng
> Yesterday 5:15 PM
> Why are all the slaves offline? http://ci.bazel.io/
> 
> Damien Martin-Guillerez
> Yesterday 6:44 PM
> No idea, I cannot investigate , <reason scrubbed, tl;dr: network access issues>
> 

Other chat with @laszlocsomor and @steren:

> Steren Giannini
> Yesterday 11:07 PM
> mattmoor@ tells me that our Bazel Jenkins is dead
> all the workers are offline
> Damien is OOO
> anybody not OOO can take a look?
> 
> László Csomor
> Yesterday 11:31 PM
> machines are online in cloud console, i can ssh into ubuntu-14-04-slave-1
> 
> László Csomor
> Yesterday 11:32 PM
> `ping jenkins` succeeds, so the master is also alive and DNS works
> 
> László Csomor
> Yesterday 11:34 PM
> I attempted to run the fix that http://ci.bazel.io/computer/ubuntu_14.04-x86_64-1/ suggests: `java -jar slave.jar -jnlpUrl http://ci.bazel.io/computer/ubuntu_14.04-x86_64-1/slave-agent.jnlp`
> 
> László Csomor
> Yesterday 11:35 PM
> from /home/ci
> command output looks good, but it hangs at "INFO: Connecting to ci.bazel.io:50000"
> 
> László Csomor
> Yesterday 11:37 PM
> i don't know how to check if port 50000 is open on jenkins-master or not
> 
> László Csomor
> Yesterday 11:39 PM
> the internet suggests using "nc"
> "nc -z jenkins 50000" succeds with exit code 0
> maybe we just need to restart the server?
> 
> László Csomor
> Yesterday 11:41 PM
> /me has to leave now
> sorry
> 
> Steren Giannini
> Yesterday 11:42 PM
> np
> thanks for investigating
> 
> Damien Martin-Guillerez
> 12:55 PM
> Gosh this is spanning over too many communication channel. So as said in the sheriff chat I cannot investigate, <scrubed, tl;dr: network issue>.
> 
> I'll be back on Monday but will probably be unable to look at that before Tuesday or Wednesday.
> (please track the investigation on a bug and log everything you are doing)
> 

Update from my side: got around network issue thanks to @meteorcloudy, I will work half a day today so I can take monday afternoon.

__Addendum__: Time in the logs are in CST (UTC -0600)

**Comment by damienmg** [comment]
I am currently cleaning-up the job queue so we do not overload the repo. We should probably restart with a run of the "Bazel job" so everything get rebuild and we have a clear view.

**Comment by damienmg** [comment]
Trying to reimage the master, maybe we are running some weird image.

**Comment by damienmg** [comment]
So `bazel run //gcr:deploy` right now, next I restart the master.

**Comment by damienmg** [comment]
(note that even the deploy slave cannot talk to the master, which excludes network issue because they run on the same machine, under separate docker container)

**Comment by damienmg** [comment]
And that worked!

**Comment by laszlocsomor** [comment]
Great job from far away! Thank you Damien :)

**Comment by damienmg** [comment]
Post-mortem info:

`docker logs b5aa` returned

```
Jul 05, 2017 8:54:23 AM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: deploy
Jul 05, 2017 8:54:23 AM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Jul 05, 2017 8:54:23 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://http://jenkins:80/, http://jenkins/]
Jul 05, 2017 8:54:23 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, JNLP-connect, Ping, JNLP2-connect]
Jul 05, 2017 8:54:23 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: jenkins
  Agent port:    50000
  Identity:      dc:ee:4d:10:2c:e8:e0:d0:4e:6e:60:9a:6b:36:b2:02
Jul 05, 2017 8:54:23 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Jul 05, 2017 8:54:23 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins:50000
Jul 05, 2017 8:54:23 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP4-connect
Jul 05, 2017 8:54:23 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Remote identity confirmed: dc:ee:4d:10:2c:e8:e0:d0:4e:6e:60:9a:6b:36:b2:02
Jul 05, 2017 8:54:24 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connected
Jul 05, 2017 8:54:24 AM hudson.remoting.AbstractByteBufferCommandTransport processCommand
WARNING: Failed to construct Command
java.io.StreamCorruptedException: invalid type code: AC
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1381)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
        at hudson.remoting.Command.readFrom(Command.java:97)
        at hudson.remoting.AbstractByteBufferCommandTransport.processCommand(AbstractByteBufferCommandTransport.java:202)
        at hudson.remoting.AbstractByteBufferCommandTransport.receive(AbstractByteBufferCommandTransport.java:188)
        at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onRead(ChannelApplicationLayer.java:186)
        at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecv(ApplicationLayer.java:207)
        at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:669)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processRead(SSLEngineFilterLayer.java:369)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecv(SSLEngineFilterLayer.java:117)
        at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:669)
        at org.jenkinsci.remoting.protocol.NetworkLayer.onRead(NetworkLayer.java:136)
        at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$2200(BIONetworkLayer.java:48)
        at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:283)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at hudson.remoting.Engine$1$1.run(Engine.java:94)
        at java.lang.Thread.run(Thread.java:745)
```

(cutted away the uninteresting part, got the id of the container with `docker ps -a` looking for the deploy-slave image)

**Comment by damienmg** [comment]
Recovering action: running the bazel job on master to retrigger the full pipeline, /cc @katre, @mhlopko fyi

**Comment by damienmg** [comment]
FTR, logs from ubuntu_14.04_x86_64-1 shows a similar failure:
```
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: WARNING: Failed to construct Command
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: java.io.StreamCorruptedException: invalid type code: AC
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1563)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at hudson.remoting.Command.readFrom(Command.java:97)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at hudson.remoting.AbstractByteBufferCommandTransport.processCommand(AbstractByteBufferCommandTransport.java:202)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at hudson.remoting.AbstractByteBufferCommandTransport.receive(AbstractByteBufferCommandTransport.java:188)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onRead(ChannelApplicationLayer.java:186)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecv(ApplicationLayer.java:207)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:669)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processRead(SSLEngineFilterLayer.java:369)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecv(SSLEngineFilterLayer.java:117)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:669)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at org.jenkinsci.remoting.protocol.NetworkLayer.onRead(NetworkLayer.java:136)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$2200(BIONetworkLayer.java:48)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:283)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at hudson.remoting.Engine$1$1.run(Engine.java:94)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: #011at java.lang.Thread.run(Thread.java:748)
Jul  5 08:55:41 ubuntu-14-04-slave-1 startup-script: INFO startup-script: Jul 05, 2017 8:55:41 AM hudson.remoting.jnlp.Main$CuiListener status
```

I am not going to look at all the slave, we seems to have a constant error in the JNLP. It seems like an image error since a restart of the server without repush resulted in the same error.

**Comment by damienmg** [comment]
2 slaves are still offlines:

* windows-x86_64-3
* darwin-x86_64-2 

Trying to remote connect to the darwin slave

**Comment by damienmg** [comment]
Apparently connecting to the darwin slave bring it back online, or maybe this was just coincidence, let's look at the windows one now

**Comment by laszlocsomor** [comment]
About the docker log (https://github.com/bazelbuild/continuous-integration/issues/86#issuecomment-313046161), any ideas why "command creation failed", and what command it refers to anyway?

About the image error (https://github.com/bazelbuild/continuous-integration/issues/86#issuecomment-313047888), any ideas what could corrupt a docker image?

**Comment by damienmg** [comment]
I have no idea either way, a wrong push could have for the docker image, I will look at the log of GCR

**Comment by damienmg** [comment]
Logs for the windows slave shows:
```
6/15/2017 4:26:29 AM UTC: Finished running startup scripts.
6/16/2017 9:56:48 PM UTC: WebException waiting for metadata change: The remote server returned an error: (503) Server Unavailable.
6/16/2017 9:56:53 PM UTC: Network access restored.
7/1/2017 2:03:18 AM UTC: WebException waiting for metadata change: The remote server returned an error: (503) Server Unavailable.
7/1/2017 2:03:24 AM UTC: Network access restored.
Build CL: 160687330
Build label: magnificent-unfolding-201706272002-rc02
Built on Fri Jun 30 14:25:31 2017 (1498857931)
Hide build data
```

Will try rebooting it.

**Comment by damienmg** [comment]
Command to pull the culprit image:
`gcloud docker -- pull gcr.io/bazel-public/jenkins-master:culprit-issue-86`

**Comment by damienmg** [comment]
Reboot reconnected the windows slave, all slaves are online now :)

**Comment by damienmg** [comment]
Apparently GCR does not have any log, maybe we should stamp images when pushing to GCR so we can track back builds from an image.

**Comment by damienmg** [comment]
Ok I have downloaded the image on my machine, looking at how fast the download went I would say it was produced on my machine.

I'll have to go somewhere, will come back online in a few hours. I'll close this bug and open a new one for investigation.
